### ISSUE TITLE
astraカメラのパラメータ

### ISSUE THREAD

**Issue by kochigami** [kochigami/my_tutorial#10]
```
(カメラノード立ち上げ)
rostopic echo /camera/rgb/camera_info

header: 
  seq: 47
  stamp: 
    secs: 1486962445
    nsecs: 213033907
  frame_id: camera_rgb_optical_frame
height: 480
width: 640
distortion_model: plumb_bob
D: [0.0, 0.0, 0.0, 0.0, 0.0]
K: [570.3422241210938, 0.0, 319.5, 0.0, 570.3422241210938, 239.5, 0.0, 0.0, 1.0]
R: [1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0]
P: [570.3422241210938, 0.0, 319.5, 0.0, 0.0, 570.3422241210938, 239.5, 0.0, 0.0, 0.0, 1.0, 0.0]
binning_x: 0
binning_y: 0
roi: 
  x_offset: 0
  y_offset: 0
  height: 0
  width: 0
  do_rectify: False
---
```
D, K, R, Pの説明はこれ
http://docs.ros.org/api/sensor_msgs/html/msg/CameraInfo.html

Dの値が入っていないようなので、キャリブレーションする。
```
(カメラノード立ち上げ)
rosrun camera_calibration cameracalibrator.py --size 8x6 --square 0.0245 image:=/camera/rgb/image_raw
```
チェッカーボードはros wikiに上がっているものをA4で印刷して使った
これにより必要なD, Kを手に入れた！
